# Generated by Django 5.0.1 on 2024-02-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OralPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tumor_size', models.FloatField()),
                ('tobacco_use', models.IntegerField()),
                ('alcohol_consumption', models.IntegerField()),
                ('reverse_smoking', models.IntegerField()),
                ('restricted_mouth_opening', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('age_group', models.IntegerField()),
                ('classification', models.IntegerField()),
            ],
        ),
    ]
